serviceConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 7177
  path: /api/idm

loggerConfig:
  outputDir: ./logs/
  outputFile: idm.log

databaseConfig:
  dbUsername: cs122b_db143
  dbPassword: IE^-pNjPoK8N
  dbHostname: localhost
  dbPort: 3307
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: cs122b_db143
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST

sessionConfig:
  timeout: 6000000
  expiration: 6000000