serviceConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 7178
  path: /api/basicService

loggerConfig:
  outputDir: ./logs/
  outputFile: basicService.log

databaseConfig:
  dbUsername: cs122b_db143
  dbPassword: IE^-pNjPoK8N
  dbHostname: localhost
  dbPort: 3307
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: cs122b_db143
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST








